# Setup
title:        Azure Afternoons
tagline:      A regular conversation with customers about cloud, projects, scenarios and more.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Azure Afternoons
  url:        http://azureafternoons.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown