# Setup
title:        Azure Afternoons
tagline:      Digging into Azure Topics with Cloud Architects all around the World.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Azure Afternoons
  url:        http://azureafternoons.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown